---
- name: Configure db host
  lineinfile:
    path: '{{ jeedom__root }}/core/config/common.config.php'
    regexp: "'host'\\s*=>.*"
    line: "'host' => '{{ jeedom__config_db_host }}',"
    insertafter: "'db'\\s*=>\\s*array\\("
  tags: ['jeedom']

- name: Configure db port
  lineinfile:
    path: '{{ jeedom__root }}/core/config/common.config.php'
    regexp: "'port'\\s*=>.*"
    line: "'port' => '{{ jeedom__config_db_port }}',"
    insertafter: "'db'\\s*=>\\s*array\\("
  tags: ['jeedom']

- name: Configure db name
  lineinfile:
    path: '{{ jeedom__root }}/core/config/common.config.php'
    regexp: "'dbname'\\s*=>.*"
    line: "'dbname' => '{{ jeedom__config_db_dbname }}',"
    insertafter: "'db'\\s*=>\\s*array\\("
  tags: ['jeedom']

- name: Configure db username
  lineinfile:
    path: '{{ jeedom__root }}/core/config/common.config.php'
    regexp: "'username'\\s*=>.*"
    line: "'username' => '{{ jeedom__config_db_username }}',"
    insertafter: "'db'\\s*=>\\s*array\\("
  tags: ['jeedom']

- name: Configure db password
  lineinfile:
    path: '{{ jeedom__root }}/core/config/common.config.php'
    regexp: "'password'\\s*=>.*"
    line: "'password' => '{{ jeedom__config_db_password }}',"
    insertafter: "'db'\\s*=>\\s*array\\("
  tags: ['jeedom']
