---

- name: Ensure jeedom group '{{ jeedom__service_group }}' is present
  group:
    name:   '{{ jeedom__service_group }}'
    system: yes
    state:  present

- name: Ensure jeedom user '{{ jeedom__service_user }}' is present
  user:
    name:       '{{ jeedom__service_user }}'
    group:      '{{ jeedom__service_group|d(jeedom__service_user) }}'
    groups:     '{{ jeedom__service_user_groups }}'
    append:     yes
    createhome: no
    system:     yes
    state:      present

- name: Ensure jeedom user '{{ jeedom__service_user }}' metadata
  user:
    name:       '{{ jeedom__service_user }}'
    group:      '{{ jeedom__service_group|d(jeedom__service_user) }}'
    home:       /nonexistent
    shell:      /sbin/nologin
    createhome: no
    system:     yes
    state:      present
  ignore_errors: yes

- name: Ensure permissions on install directory
  file:
    dest:    '{{ jeedom__install_directory }}'
    owner:   '{{ jeedom__service_user }}'
    group:   '{{ jeedom__service_group }}'
    mode:    'u=rwX,g=rwX,o=rX'
    recurse: yes
    state:   directory

- name: Create customs directories
  file:
    dest:  '{{ item }}'
    owner: '{{ jeedom__service_user }}'
    group: '{{ jeedom__service_group }}'
    mode:  '0775'
    state: directory
  with_items: '{{ jeedom__custom_folders }}'

### Configure sudo rights
- name: Configure sudoers rights for Jeedom
  lineinfile:
    path:     /etc/sudoers
    regexp:   '^{{ jeedom__service_user }} ALL='
    line:     '{{ jeedom__service_user }} ALL=(ALL:ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
    state:    present
  when: not jeedom__sudo_use_sudoers_role|bool

- name: Configure sudoers rights for Jeedom
  include_role:
    name: sudoers
    tasks_from: types/sudo_rule
  vars:
    sudoers__sudo_rule:
      name: jeedom_01
      users: '{{ jeedom__service_user }}'
      hosts: ALL
      comment: 'Allow jeedom web user to run any commands'
      commands:
        - commands: ALL
          run_as_user: ALL
          tags: NOPASSWD
      defaults:
        - defaults: '!requiretty'
          user: '{{ jeedom__service_user }}'
        - defaults: '!requiretty'
          user: 'root'
        - listpw: never
          user: '{{ jeedom__service_user }}'
      state: present
  when: jeedom__sudo_use_sudoers_role|bool

### PHP TODO move to a dedicated role
- name: Search for php.ini in /etc
  find:
    paths:     '/etc/'
    patterns:  'php.ini'
    file_type: file
    recurse:   yes
  register: _jeedom__find_php_inis
  check_mode: no

- name: Configure php.ini
  lineinfile:
    path:   '{{ item[0] }}'
    regexp: '{{ item[1].regexp }}'
    line:   '{{ item[1].line }}'
  with_nested:
    - "{{ _jeedom__find_php_inis.files|map(attribute='path') | list }}"
    - '{{ jeedom__php_directives }}'

- import_tasks: configure-jeedom.yml
  tags: ['jeedom', 'jeedom-configure-jeedom']
