---

- name: Create custom fact directory
  file:
    path: "{{ facts__dir|d('/etc/ansible/facts.d') }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags: ['jeedom', 'jeedom-facts']

- name: Insert custom fact file
  template:
    src: jeedom.facts.py.j2
    dest: "{{ facts__dir|d('/etc/ansible/facts.d') }}/jeedom.fact"
    owner: root
    group: root
    mode: 0755
  tags: ['jeedom', 'jeedom-facts']
