---

- name: Install the jeedom required packages
  package:
    name:  '{{ item }}'
    state: present
  with_items: '{{ jeedom__packages_names }}'

- name: Test for Jeedom installation
  stat:
    path:   '{{ jeedom__install_directory }}/composer.json'
  register: _jeedom__install_status

- name: List default files when jeedom is not installed
  find:
    paths:     '{{ jeedom__install_directory }}'
    file_type: file
  when: not _jeedom__install_status.stat.exists
  register: _jeedom__install_files

- name: Remove default files when jeedom is not installed
  file:
    path:  '{{ item.path }}'
    state: absent
  with_items: '{{ _jeedom__install_files.files }}'
  when: not _jeedom__install_status.stat.exists

- name: Install jeedom from release archive
  unarchive:
    src:        '{{ jeedom__install_archive_url }}'
    dest:       '{{ jeedom__install_directory }}'
    extra_opts: --strip-components=1
    remote_src: yes
  when: not _jeedom__install_status.stat.exists
