---

- name: Install the jeedom required packages
  package:
    name:  '{{ item }}'
    state: present
  with_items: '{{ jeedom__packages_names }}'

- name: Test for Jeedom installation
  stat:
    path:   '{{ jeedom__install_directory }}/composer.json'
  register: _jeedom__install_status

- name: Remove default directory when jeedom is not installed
  file:
    path:  '{{ jeedom__install_directory }}'
    state: absent
  when: not _jeedom__install_status.stat.exists

- name: Checkout Jeedom source from repository
  git:
    repo:    '{{ jeedom__install_repository_url }}'
    dest:    '{{ jeedom__install_directory }}'
    version: '{{ jeedom__install_version }}'
    clone:   True
    update:  False
  when: not _jeedom__install_status.stat.exists
